config/routes.rb
Rails.application.routes.draw do
  root 'billboards#index'

  resources :billboards do
    resources :artists
  end
  
  resources :artists do
    resources :songs
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard, optional: true
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_billboard
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = @billboard.artists
  end

  def show
  end

  def new
    @artist = @billboard.artists.new
  end

  def edit
  end

  def create
    @artist = @billboard.artists.new(artist_params)
    if @artist.save
      redirect_to billboard_artist_path(@billboard, @artist)
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to billboard_artist_path(@billboard, @artist)
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to billboard_artist_path
  end

  private

    def artist_params
      params.require(:artist).permit(:name, :body)
    end

    def set_billboard
      @billboard = Billboard.find(params[:billboard_id])
    end

    def set_artist
      @artist = @billboard.artist.find(params[:id])
    end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy]


  def index
    @billboards = Billboard.all
  end


  def show
  end


  def new
    @billboard = Billboard.new
    render partial: "form"
  end


  def edit
    render partial: "form"
  end

  #POST /subs
  def create
    @billboard = Billboard.new(billboard_params)

    if @billboard.save
      redirect_to billboards_path(@billboard)
    else
      render partial: "form"
    end
  end


  def update
    if @billboard.update(billboard_params)
      redirect_to billboard_path(@billboard)
    else
      render partial: "form"
    end
  end

  #DELETE /subs/:id
  def destroy
    @billboard.destroy
    redirect_to billboard_path
  end

  private
    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def billboard_params
      params.require(:billboard).permit(:title)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @artist.song
  end

  def show
  end

  def new
    @song = @artist.songs.new
  end

  def edit
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_song_path(@artist, @song)
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to artist_song_path(@artist, @song)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_song_path
  end

  private

    def song_params
      params.require(:song).permit(:name, :body)
    end

    def set_artist
      @billboard = Artist.find(params[:artist_id])
    end

    def set_song
      @song = @artist.song.find(params[:id])
    end

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit Billboard' : 'Create Billboard'%></h1>
<hr />
<%= form_for @billboard do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/billboards/index.html.erb
<h1>Click a Billboard to view</h1>
<%= link_to 'Add a New Billboard', new_billboard_path %>
<hr />
<ul>
  <% @billboards.each do |billboard| %>
    <li><%= link_to billboard.name, billboard_path(billboard) %></li>
    <% end %>
</ul>

app/views/billboards/show.html.erb
<h1><%= @billboard.name %></h1>
<hr />
<p>What would you like to do?</p>
<br />
<%= link_to 'View Billboards', billboard_path(@billboard) %>
<br />
<%= link_to 'Edit Billboards', edit_billboard_path(@billboard) %>
<br />
<%= link_to 'Delete Billboards', billboard_path(@billboard), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Click a song</h1>
<%= link_to 'Add a song', new_sub_topic_path(@sub) %>
<ul>
  <% @songs.each do |topic| %>
    <li><%= link_to topic.name, [@sub, @topic] %></li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>